name: setup-kind

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./

concurrency:
  group: test-github-action${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test-github-action:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Keep running if one leg fails.
      matrix:
        k8s-version:
        - 1.25.x
        - 1.26.x
        - 1.27.x
        - 1.28.x
        - 1.29.x
        - 1.30.x

        # See https://github.com/chainguard-dev/actions/pull/175
        # We're testing whether setting a custom cluster domain works
        cluster-suffix:
        - cluster.local # default value
        - potato.local

        include: 
        - k8s-version: 1.25.x
          knative-version: 1.11.0          
        - k8s-version: 1.26.x
          knative-version: 1.12.0
        - k8s-version: 1.27.x
          knative-version: 1.13.0
        - k8s-version: 1.28.x
          knative-version: 1.13.0
        - k8s-version: 1.29.x
          knative-version: 1.13.0
        - k8s-version: 1.30.x
          knative-version: 1.13.0

    steps:
    - uses: step-security/harden-runner@int-sh
      with:
        egress-policy: audit
        allowed-endpoints: >
          9236a389bd48b984df91adc1bc924620.r2.cloudflarestorage.com:443
          api.github.com:443
          auth.docker.io:443
          cdn03.quay.io:443
          cgr.dev:443
          gcr.io:443
          github.com:443
          mirror.gcr.io:443
          objects.githubusercontent.com:443
          packages.wolfi.dev:443
          production.cloudflare.docker.com:443
          quay.io:443
          raw.githubusercontent.com:443
          registry-1.docker.io:443
          storage.googleapis.com:443
    
    #- name: Run iptables commands to delete rules
    #  run: |
    #    sudo iptables -D OUTPUT -o eth0 -p udp --dport 53 -d 168.63.129.16 -j DROP
    #    sudo iptables -D DOCKER-USER -i docker0 -p udp --dport 53 -d 168.63.129.16 -j DROP
    
    - name: Clear per-link DNS settings
      run: |
        # Get a list of active network interfaces
        interfaces=$(resolvectl status | grep 'Link' | awk '{print $2}')
        
        # Clear DNS settings for each interface
        for iface in $interfaces; do
          echo "Clearing DNS settings for interface $iface"
          sudo resolvectl dns $iface ''
          sudo resolvectl domain $iface ''
          sudo resolvectl default-route $iface no
        done
        sudo systemctl restart systemd-resolved
    - run: cat /run/systemd/resolve/resolv.conf
    - name: Checkout the current action
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - uses: ./whereami # Log where I am.

    - id: changed-kind
      uses: tj-actions/changed-files@e9772d140489982e0e3704fea5ee93d536f1e275 # v45.0.1
      with:
        files: |
          ./setup-kind/**
          ./setup-knative/**
          .github/workflows/test-setup-kind.yaml

    - name: setup-kind
      if: steps.changed-kind.outputs.any_changed == 'true'
      uses: ./setup-kind
      with:
        k8s-version: ${{ matrix.k8s-version }}
        cluster-suffix: ${{ matrix.cluster-suffix }}

    - name: check domain
      if: steps.changed-kind.outputs.any_changed == 'true'
      run: |
        expected_value="${{ matrix.cluster-suffix }}"
        dnsDomain=$(docker exec kind-control-plane cat /kind/kubeadm.conf | { grep dnsDomain || true; } | awk '{ print $2 }')

        if [[ "${expected_value}" == "cluster.local" ]]; then
          # the action doesn't explicitly set cluster.local - so we expect an empty value
          if [[ -n "${dnsDomain}" ]]; then
            echo "Cluster domain was set to '${dnsDomain}' instead of 'cluster.local'"
            exit 1
          fi
        else
          if [[ -z "${dnsDomain}" ]]; then
              echo "Cluster domain was not set - expected: '${expected_value}'"
              exit 1
          elif [[ "${expected_value}" != "${dnsDomain}" ]]; then
              echo "Cluster domain expected: '${expected_value}' - actual: '${dnsDomain}'"
              exit 1
          fi
        fi

    - name: Test spinning up Knative
      if: ${{ steps.changed-kind.outputs.any_changed == 'true' }}
      uses: ./setup-knative
      with:
        version: ${{ matrix.knative-version || 'latest' }}

    - run: sudo iptables -L -v -n
      if: ${{ always() }}
    
    - name: Collect diagnostics
      if: ${{ failure() }}
      uses: chainguard-dev/actions/kind-diag@main
      with:
        artifact-name: logs.${{ matrix.k8s-version }}
